kind: Service
apiVersion: v1
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  type: NodePort 
  ports:
  - port: 9090
    targetPort: 9090 
    name: http
    nodePort: 30000
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
        version: v1
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:v2.22.1
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: prometheus-config-volume
        configMap:
          name: prometheus-config
      restartPolicy: Always
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s

      external_labels:
        monitor: 'check-url-monitor'

    scrape_configs:
    - job_name: 'check-url-metric'
      scrape_interval: 5s
      metrics_path: '/metrics'
      static_configs:
      - targets: ['check-url:8080']
      scheme: http
---
